### ISSUE TITLE
orchestra: TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by mewmew** [revng/revamb#2]
I tried to compile revamb using orchestra, but when doing so received the following error:

```
u@x220 ~/D/r/orchestra> ./bootstrap.sh 
+ /home/u/Desktop/revng_play/orchestra/repo-rehab clone --branch develop
Traceback (most recent call last):
  File "/home/u/Desktop/revng_play/orchestra/repo-rehab", line 109, in <module>
    main()
  File "/home/u/Desktop/revng_play/orchestra/repo-rehab", line 69, in main
    remotes = launch(["git", "remote"])
  File "/home/u/Desktop/revng_play/orchestra/repo-rehab", line 27, in launch
    return subprocess.check_output(argv).strip().split("\n")
TypeError: a bytes-like object is required, not 'str'
```

Python version:
```
u@x220 ~/D/r/orchestra> python --version
Python 3.6.0
```

**Comment by aleclearmind** [comment]
Try with Python 2. If you still have problems, please open an issue on the [orchestra repository](https://github.com/revng/orchestra), not here.
